### ISSUE TITLE
Chess Timer

### ISSUE THREAD

**Issue by ramou** [ramou/ChessMod#53]
Play Times games. Make this applicable to either Gold Chessboard and above. For the gold board, start the timer after the first move. In other boards, the black player starts the timer, when present, which allows white to begin.

 * Gold Chessboard: just track time, per side and per turn, since board reset. Display on board.
 * Tournament Chessboard ([Time Control](https://en.wikipedia.org/wiki/Time_control)):
  * [ ] `Sudden Death`: Each side is assigned total allowed time for the whole game. Passing time is a loss. #50 
  * [ ] `Canadian Overtime`: _We're implementing this format, eh_. Once overtime is reached, players must play subsequent batches of moves in a fixed time. Configure defaults in mod, allow setup via timer. #51
  * [ ] `Hourglass`: As one player's time decreases, the others increases. Loss if you run out of time on your play. #52

When configuring a timer, the specific times for various time-related things on the board should be adjustable. Time until a challenge can be revoked and time until a completed board can be reset come to mind, but there may be others. A timer should allow the reset of all mod-specific timing defaults in the config. 

The timer configuration should persist when a timer is broken, so if played on another chessboard it will apply.

## Question
I'm on the fence whether the timer should be played next to the board, forming a multiblock, or whether it should merge with the board block, detaching (while saving its state) when the chessboard is broken. TDB. What to do?
